all:
  hosts:
    'family-room-tv.local':
        ansible_user: pi
        ansible_password: MarshRasp1
        room_assistant_config:
          global:
            bluetoothLowEnergy:
              maxDistance: 6
            cluster:
              weight: 2
    'study.local':
        ansible_user: pi
        ansible_password: MarshRasp1
        room_assistant_config:
          global:
            bluetoothLowEnergy:
              maxDistance: 5
            cluster:
              weight: 3
    'tobys-room.local':
        ansible_user: pi
        ansible_password: MarshRasp1
        room_assistant_config:
          global:
            bluetoothLowEnergy:
              maxDistance: 7
            cluster:
              weight: 2
    'kitchen.local':
        ansible_user: pi
        ansible_password: MarshRasp1
        room_assistant_config:
          global:
            bluetoothLowEnergy:
              maxDistance: 5
            cluster:
              weight: 2
  vars:
    room_assistant_version: latest
    room_assistant_global_config:
      global:
        integrations:
          - homeAssistant
          - bluetoothLowEnergy
      homeAssistant:
        mqttUrl: mqtt://tower.local:1883
        mqttOptions:
          username: room-assistant
          password: MarshMqtt1
      cluster:
        networkInterface: wlan0
        quorum: 3
        port: 6425
        peerAddresses:
          - 192.168.1.237:6425
          - 192.168.1.200:6425
          - 192.168.1.183:6425
          - 192.168.1.107:6425
      bluetoothLowEnergy:
        whitelist:
          - f7693b8331ed
          - d5dc0677804c
          - ef8a791491ec
        timeout: 20
        tagOverrides:
          f7693b8331ed:
            name: Toby Mi Band
          d5dc0677804c:
            name: Philip Mi Band
          ef8a791491ec:
            name: Vanessa Mi Band
      
