---
- name: Download NodeJS
  get_url:
    url: 'https://unofficial-builds.nodejs.org/download/release/{{ nodejs_armv6l_version }}/node-{{ nodejs_armv6l_version }}-linux-armv6l.tar.gz'
    dest: '~/node-{{ nodejs_armv6l_version }}-linux-armv6l.tar.gz'
    checksum: 'sha256:https://unofficial-builds.nodejs.org/download/release/{{ nodejs_armv6l_version }}/SHASUMS256.txt'
    force: no
  notify: "Reinstall NodeJS"
- name: Flush handlers
  meta: flush_handlers
- name: Add npm module binaries to PATH
  lineinfile:
    dest: ~/.profile
    state: present
    line: 'PATH="$PATH:/opt/nodejs/bin"'